site_name: Bengali YouTube Transcription
site_description: An automated, low-latency Bengali speech-to-text pipeline evaluating multiple fine-tuned Whisper architectures.
repo_name: JyotismoyKalita/BengaliYoutubeTranscription
repo_url: https://github.com/JyotismoyKalita/BengaliYoutubeTranscription
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
  palette:
    primary: indigo
    accent: deep purple

nav:
  - Home: index.md
  - Model Compilation Guide: Model_Guide.md
  - Detailed Progress Report: Progress_Report.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_mermaid_custom
