site_name: Bengali YouTube Transcription
site_description: An automated, low-latency Bengali speech-to-text pipeline evaluating multiple fine-tuned Whisper architectures.
repo_name: JyotismoyKalita/BengaliYoutubeTranscription
repo_url: https://github.com/JyotismoyKalita/BengaliYoutubeTranscription
theme:
  name: material
  logo: assets/logo-light.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
  palette:
    # Light Mode Configuration
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark Mode Configuration
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Project Report: index.md
  - Setup & Installation Guide: Setup_Guide.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
